name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: run all the tests
    runs-on: ubuntu-18.04
    steps:
      - name: prepare repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: dependencies
        run:
          pip install -r tests/requirements.txt
      - name: pytest
        run:
          python -m pytest tests/
      - name: verify that all entry points can be run
        run: |
          python -m pokestrings strings --help
          python -m pokestrings codec --help
      - name: verify pip installation
        run: |
          pip install .
          pokestrings --help
          pokecodec --help
